### PR TITLE
WIP state machine bring up

### PR DESCRIPTION
**Pull request by uditvira**
Made the following changes:
* coins needed to be in ascending order by denom
* token pool mismatch fixed by changing bond status
* increased max_validators param in staking module when we add a new validator instead of replacing the smallest one

### CODE REVIEW

**Comment by uditvira** [comment]
Made lots of progress, but currently facing this issue: 
```
Feb 13 18:32:00 hydrogen cosmovisor[378133]: panic: len(RequestInitChain.Validators) != len(GenesisValidators) (151 != 150)
Feb 13 18:32:00 hydrogen cosmovisor[378133]: goroutine 1 [running]:
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000db41a0, 0x0, 0xed5830c36, 0x0, 0xc0005aa2c0, 0xd, 0xc0005a8ce0, 0xc0005b7000, 0x97, 0x97, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:67 +0x98d
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00001b860, 0x0, 0xed5830c36, 0x0, 0xc0005aa2c0, 0xd, 0xc0005a8ce0, 0xc0005b7000, 0x97, 0x97, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x115
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000cf7670, 0x0, 0xed5830c36, 0x0, 0xc0005aa2c0, 0xd, 0xc0005a8ce0, 0xc0005b7000, 0x97, 0x97, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x78
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000fbfc18, 0xb, 0x0, 0x23593f8, 0x8, 0xc0005aa2c0, 0xd, 0x89dbae, 0x0, 0x0, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0x655
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000fbfc18, 0x23e1568, 0xc0000f81a0, 0x1f4, 0xc000cf7920)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x458
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/tendermint/tendermint/node.doHandshake(0x23dd088, 0xc001076c10, 0xb, 0x0, 0x23593f8, 0x8, 0xc0005aa2c0, 0xd, 0x89dbae, 0x0, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1d8
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/tendermint/tendermint/node.NewNode(0xc000c06c80, 0x23bdad0, 0xc000543040, 0xc000eda0e0, 0x2386320, 0xc00000ff20, 0xc000eda150, 0x2174758, 0xc000eda240, 0x23c7640, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x2105
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000d52320, 0x0, 0x0, 0x0, 0x23ead58, 0xc0005a5cb0, 0x0, 0x0, 0x23d0bb0, 0xc0010b73e0, ...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/cosmos/cosmos-sdk@v0.44.3/server/start.go:263 +0x685
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001129400, 0xc000d41c80, 0x0, 0x3, 0x0, 0x0)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/cosmos/cosmos-sdk@v0.44.3/server/start.go:129 +0x209
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/spf13/cobra.(*Command).execute(0xc001129400, 0xc000d41c20, 0x3, 0x3, 0xc001129400, 0xc000d41c20)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/spf13/cobra.(*Command).ExecuteC(0xc001084500, 0x0, 0x0, 0xc00107fb80)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/spf13/cobra@v1.2.1/command.go:902
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/spf13/cobra@v1.2.1/command.go:895
Feb 13 18:32:00 hydrogen cosmovisor[378133]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc001084500, 0xc00107fb80, 0x10, 0x23e34f8, 0xc0010b73e0)
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/cosmos/cosmos-sdk@v0.44.3/server/cmd/execute.go:36 +0x285
Feb 13 18:32:00 hydrogen cosmovisor[378133]: main.main()
Feb 13 18:32:00 hydrogen cosmovisor[378133]:         github.com/cosmos/gaia/v6/cmd/gaiad/main.go:16 +0x45
```

**Comment by uditvira** [comment]
getting this error now:
```
Feb 15 14:06:54 hydrogen cosmovisor[452170]: panic: genesisValidators[49] != req.Validators[49]
Feb 15 14:06:54 hydrogen cosmovisor[452170]: goroutine 1 [running]:
Feb 15 14:06:54 hydrogen cosmovisor[452170]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00123c000, 0x0, 0xed5830c36, 0x0, 0xc000f30190, 0xd, 0xc000b74bc0, 0xc00117d000, 0x96, 0x96, ...)
```

These are the relevant modifications I’ve made:

- Swap chain id to theta-testnet
- Increase bank balance of cosmos1lapm2cq4qjrl4fm5xcftfhg245m63d30mswfjp by 175000000000000 uatom. These are liquid tokens for the faucet
- Increase bank supply by 175000000000000 uatom. These are liquid tokens corresponding to the previous step.
- Find the smallest validator in the genesis validators and replace it with our validator and change validator power to 550000001 (550000000 + 1, the +1 is because there was a single atom self-delegated when the genesis was exported)
- Modify total power: increase by 550000001 and subtract the power of the smallest validator that we kicked out of the validator set
- Increasing bank balance of cosmos1fl48vsnmsdzcv85q5d2q4z5ajdha8yu34mf0eh by 550000001000000 uatom (Module Account of “token bonding pool”). Decrease balance of cosmos1tygms3xhhs3yv487phx3dw4a95jn7t7lpm470r by -1000000 uatom (Module Account for “not bonding pool”). Change status to “BOND_STATUS_BONDED”
- Increasing bank supply of uatom by 550000000000000 corresponding to the previous increase.
- In distribution module starting info’s, increasing delegator stake of cosmos1lapm2cq4qjrl4fm5xcftfhg245m63d30mswfjp by 550000000000000. This is a self delegation.
- In distribution module, increasing validator stake of cosmosvaloper1lapm2cq4qjrl4fm5xcftfhg245m63d307y6u7j by 550000000000000
- Decrease balance of cosmos1fl48vsnmsdzcv85q5d2q4z5ajdha8yu34mf0eh by 20451888836 uatom (“token bonding pool”). This amount corresponds to the tokens bonded by the smallest validator. When we kicked out the smallest validator, we’re unbonding it’s atoms and changing its status to “BOND_STATUS_UNBONDED”. Correspondingly we increase the balance of cosmos1tygms3xhhs3yv487phx3dw4a95jn7t7lpm470r by 20451888836 uatom (Module Account for “not bonding pool”)


I believe this is the relevant bit of code where the node panics: https://github.dev/cosmos/cosmos-sdk/blob/7869d38e94d5e691f453880d1be40af60121b85a/baseapp/abci.go#L79-L80
If I’m reading code correctly, the issue is that the genesis validators don’t match the validators specified by the app. I’ve looked at the validators in the state of the staking module and compared them with the genesis validators, and checked that the pub keys are identical and the delegator shares correspond to the power levels.

**Comment by uditvira** [comment]
ok managed to solve the issue by updating the last_validator_powers in the staking module

**Comment by uditvira** [comment]
getting this:

```
ERR CONSENSUS FAILURE!!! err="Expected signing info for validator cosmosvalcons1uhp2lxfjyzeqpswgd6pmhcr2xhukpwpfheam88 but not found" module=consensus stack="goroutine 31 [running]:\nruntime/debug.Stack(0xc01b95c760, 0x1c09460, 0xc01c5d1800)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc000198380, 0x2174648)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:726 +0x5b\npanic(0x1c09460, 0xc01c5d1800)\n\truntime/panic.go:965 +0x1b9\ngithub.com/cosmos/cosmos-sdk/x/slashing/keeper.Keeper.HandleValidatorSignature(0x23a92d0, 0xc000c09060, 0x23dd558, 0xc0010f3a30, 0x23d7690, 0xc00017f550, 0x23cb200, 0xc000c10e40, 0x23c68e8, 0xc00018a010, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/slashing/keeper/infractions.go:25 +0x2417\ngithub.com/cosmos/cosmos-sdk/x/slashing.BeginBlocker(0x23c68e8, 0xc00018a010, 0x23e0300, 0xc01b930400, 0xb, 0x0, 0xc01b759070, 0xd, 0x89dbaf, 0x2efc66c2, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/slashing/abci.go:23 +0x265\ngithub.com/cosmos/cosmos-sdk/x/slashing.AppModule.BeginBlock(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/x/slashing/module.go:168\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc0010e9500, 0x23c68e8, 0xc00018a010, 0x23e0300, 0xc01b930400, 0xb, 0x0, 0xc01b759070, 0xd, 0x89dbaf, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:450 +0x1d8\ngithub.com/cosmos/gaia/v6/app.(*GaiaApp).BeginBlocker(...)\n\tgithub.com/cosmos/gaia/v6/app/app.go:628\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000196000, 0xc01b924a20, 0x20, 0x20, 0xb, 0x0, 0xc01b759070, 0xd, 0x89dbaf, 0x2efc66c2, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:193 +0x7b8\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000232ea0, 0xc01b924a20, 0x20, 0x20, 0xb, 0x0, 0xc01b759070, 0xd, 0x89dbaf, 0x2efc66c2, ...)\n\tgithub.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0xfa\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc001424900, 0xc01b924a20, 0x20, 0x20, 0xb, 0x0, 0xc01b759070, 0xd, 0x89dbaf, 0x2efc66c2, ...)\n\tgithub.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x75\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x23c7640, 0xc0068da720, 0x23d40f8, 0xc001424900, 0xc00000d0e0, 0x23dd088, 0xc000030680, 0x89dbae, 0xc034e548c0, 0x20, ...)\n\tgithub.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x51b\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000d82a10, 0xb, 0x0, 0xc01cd50ea0, 0x8, 0xc01cd50eb0, 0xd, 0x89dbae, 0x89dbae, 0xc034e548c0, ...)\n\tgithub.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x168\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000198380, 0x89dbaf)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1635 +0xb48\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000198380, 0x89dbaf)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1546 +0x428\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0xc000198380, 0xc000000000, 0x89dbaf)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1481 +0x8e\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000198380, 0x89dbaf, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1519 +0x6be\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000198380, 0xc010393400, 0x0, 0x0, 0xe327de7e, 0x8fe7d49d15ab69c1, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:2132 +0xde5\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000198380, 0xc010393400, 0x0, 0x0, 0x1f08fe6, 0xf, 0x31585a0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:1930 +0x56\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000198380, 0x23861a0, 0xc00fe831d8, 0x0, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:838 +0x96d\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000198380, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.14/consensus/state.go:782 +0x605\ncreated by github.com/tendermint/ten
```

**Review by RangerMauve — APPROVED** [review]

**Pull request merged**
