### PR TITLE
Initial implementation of genesis tinkerer

### PR DESCRIPTION
**Pull request by RangerMauve**
Before merging:

- Add governance parameters
- Add `Validator` class to track all validator info in an object

### CODE REVIEW

**Comment by uditvira** [comment]
power is being returned as a float and not int. this needs to be fixed:
Screen Shot 2022-02-09 at 10 19 08 AM

**Comment by uditvira** [comment]
I'm also getting this error:

```
Feb 09 15:43:17 hydrogen cosmovisor[37930]: panic: unknown field "delegator_address" in types.Validator
Feb 09 15:43:17 hydrogen cosmovisor[37930]: goroutine 1 [running]:
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0010bf900, 0xc01c566000, 0x1ba0a23, 0x1ba2000, 0x23b65d0, 0xc000d10fd0)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/codec/proto_codec.go:176 +0x98
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis(0x23e34f8, 0xc0010bf900, 0x23a92d0, 0xc000c5a490, 0x23dd558, 0xc0010bf900, 0x23caf80, 0xc0000da5a0, 0x7f0ba9a563d8, 0xc00015a580, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/x/staking/module.go:151 +0xa4
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000d8e230, 0x23c68e8, 0xc00011a010, 0x23e0300, 0xc000c4a380, 0x0, 0x0, 0xc001230040, 0x1d, 0x706ec3, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:307 +0x2b5
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/gaia/v6/app.(*GaiaApp).InitChainer(0xc0000bc000, 0x23c68e8, 0xc00011a010, 0x23e0300, 0xc000c4a380, 0x0, 0x0, 0xc001230040, 0x1d, 0x706ec3, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/gaia/v6/app/app.go:645 +0x230
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000124000, 0x0, 0xed5830c36, 0x0, 0xc001230040, 0x1d, 0xc0012534e0, 0xc000d26c00, 0x7d, 0x7d, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:62 +0x315
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0011ab920, 0x0, 0xed5830c36, 0x0, 0xc001230040, 0x1d, 0xc0012534e0, 0xc000d26c00, 0x7d, 0x7d, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x115
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000c5a200, 0x0, 0xed5830c36, 0x0, 0xc001230040, 0x1d, 0xc0012534e0, 0xc000d26c00, 0x7d, 0x7d, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x78
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000edfc18, 0xb, 0x0, 0x23593f8, 0x8, 0xc001230040, 0x1d, 0x706ec3, 0x0, 0x0, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0x655
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000edfc18, 0x23e1568, 0xc00007c1a0, 0x1f4, 0xc000232930)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x458
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/tendermint/tendermint/node.doHandshake(0x23dd088, 0xc000d20990, 0xb, 0x0, 0x23593f8, 0x8, 0xc001230040, 0x1d, 0x706ec3, 0x0, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1d8
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/tendermint/tendermint/node.NewNode(0xc0011112c0, 0x23bdad0, 0xc0005cb680, 0xc000111ad0, 0x2386320, 0xc00000ff50, 0xc000111bf0, 0x2174758, 0xc000111d70, 0x23c7640, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x2105
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0011dc1e0, 0x0, 0x0, 0x0, 0x23ead58, 0xc0011d9920, 0x0, 0x0, 0x23d0bb0, 0xc0010bf900, ...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/server/start.go:263 +0x685
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00114cf00, 0xc0011d8c00, 0x0, 0x3, 0x0, 0x0)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/server/start.go:129 +0x209
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/spf13/cobra.(*Command).execute(0xc00114cf00, 0xc0011d8ba0, 0x3, 0x3, 0xc00114cf00, 0xc0011d8ba0)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/spf13/cobra.(*Command).ExecuteC(0xc001136000, 0x0, 0x0, 0xc0010a3ce0)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/spf13/cobra@v1.2.1/command.go:902
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/spf13/cobra@v1.2.1/command.go:895
Feb 09 15:43:17 hydrogen cosmovisor[37930]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc001136000, 0xc0010a3ce0, 0x10, 0x23e34f8, 0xc0010bf900)
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/cosmos-sdk@v0.44.3/server/cmd/execute.go:36 +0x285
Feb 09 15:43:17 hydrogen cosmovisor[37930]: main.main()
Feb 09 15:43:17 hydrogen cosmovisor[37930]:         github.com/cosmos/gaia/v6/cmd/gaiad/main.go:16 +0x45
```

**Comment by RangerMauve** [comment]
@uditvira The issue with the "delegator_address" is due to a small spelling error on this line: https://github.com/hyphacoop/cosmos-genesis-tinkerer/pull/1/commits/905f8c13e98904b62ed63bb7f5bcb710cd2106ee#diff-f133887044f3b9bb28900720d554de66c391f97c27d00688b0d1e1514ace1f16L562

Changed the power thing to be `["power"] = str(int(new_power))` which will hopefully help.

**Comment by uditvira** [comment]
lgtm <3

**Pull request merged**
